### ISSUE TITLE
Dart Error: error: import of dart:mirrors

### ISSUE THREAD

**Issue by mlivi25** [syberside/Activatory#51] opened 2021-03-01 02:37 UTC
I think you're package is exactly what I am looking for however, whenever attempt to run a test using it I get the following error messages in my console:

Shell: [ERROR:flutter/shell/common/shell.cc(210)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
Shell: [ERROR:flutter/shell/common/engine.cc(220)] Could not prepare to run the isolate.
Shell: [ERROR:flutter/shell/common/engine.cc(159)] Engine not prepare and launch isolate.
Shell: [ERROR:flutter/shell/common/shell.cc(491)] Could not launch engine with configuration.

**Comment by syberside** [comment] 2021-03-01 10:15
Hi @Legz4Dayz!
This is expected behaviour because current implementation is based on dart:mirrors (reflection) which is not supported by flutter runtime.

You can resolve this by splitting your project into two pieces (projects) 
1. UI application that is using flutter runtime without any logic inside. 
2. Businesses logic library that is using dart runtime and require unit tests
This will allow you to use Activatory in second project.

**Comment by syberside** [comment] 2021-03-07 17:04
Closing the issue because of innactivity. If you need any futher help with Activatory feel free to reopen issue or create new one.

**Closed as completed by syberside** 2021-03-07 17:04 UTC
